version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8097:8097"
    volumes:
      - .:/usr/src/app
    command: air cmd/main.go -b 0.0.0.0
    depends_on:
      - database
  database:
      image: postgres:alpine
      restart: always
      ports:
          - "5432:5432"
      volumes:
        - ./migrations/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
  adminer:
    image: adminer
    restart: always
    ports:
      - "8282:8080"
    depends_on:
      - database
volumes:
  database: